### PR TITLE
2 things: 1. Windows build support. 2. CMake Support

### PR DESCRIPTION
**Pull request by Marcus10110**
Hello!

I was just helping another Saleae user build and use this analyzers for Windows. In the process, I fixed a few minor issues that were blocking the build on Windows.

1. I replaced `bzero` with `std::fill`. Note, std::fill might bump the required gcc version a bit, not sure when support as added for that.
2. `srand` used to be seeded with `-time(NULL) ^ getpid()`, I just plugged in zero.

I also added CMake support for building the analyzer cross platform. The included cmake script also handles downloading the analyzer SDK, so that doesn't need to be downloaded independently anymore. Details can be found in the readme.

No worries if you don't want to merge all of this, I just thought it might help to avoid confusion about using the original vs the fork.

### CODE REVIEW

**Comment by dirkx** [comment]
Does windows support something like below:

‘’'
   #include <random>
   #include <iostream>
   
  int main() {
    std::random_device r;
    unsigned int seed = r();
    ....

**Comment by Marcus10110** [comment]
Yup that works!

**Comment by dirkx** [comment]
Splendid - could you merge that into the code as well - and I'll merge that PR too then,

Dw.

**Comment by Marcus10110** [comment]
Just added the rand() replacement to the other PR.

**Pull request merged**
